### ISSUE TITLE
Create a login with twitter button on Navbar along side github button for desktop screen only

### ISSUE THREAD

**Issue by Aadarsh805** [Aadarsh805/TweetSage#11]

**Comment by stephenokyere233** [comment]
I'd love to do this one

**Comment by Aadarsh805** [comment]
> I'd love to do this one

Sure sir go ahead, assigned you

**Comment by stephenokyere233** [comment]
Alright I'll update you in the evening my time

**Comment by Aadarsh805** [comment]
> Alright I'll update you in the evening my time

Sure take your time
