### ISSUE TITLE
Adding a modal or dropdown and showing example questions on mobile screen too

### ISSUE THREAD

**Issue by Aadarsh805** [Aadarsh805/TweetSage#74]
Currently the examples components is only visible on larger screens because it was talking a lot of space in mobile screen 
![image](https://user-images.githubusercontent.com/95094057/208488568-df18d262-8e6b-488c-bd12-4a1de2dfb677.png)

what I'd like to do (only for mobile screen) is add a small button which opens the examples in a modal or a select dropdown on question input itself like this 

![iPhone 14 - 1](https://user-images.githubusercontent.com/95094057/208492442-d5d7237c-6568-4888-926d-37f4acaae32f.png)

**Comment by sboy99** [comment]
Hey can I use headlessui to tackle this issue??

**Comment by Aadarsh805** [comment]
> Hey can I use headlessui to tackle this issue??

you can use materialUI, we are already using materialUI in several places
