### ISSUE TITLE
Twitter profile username not detected and marked as invalid

### ISSUE THREAD

**Issue by Nishantjain10** [Aadarsh805/TweetSage#75]
![image](https://user-images.githubusercontent.com/89480234/208496200-c498f57d-b3fb-4491-9801-db22bf2e1ba3.png)
![image](https://user-images.githubusercontent.com/89480234/208496463-33d1571c-d43e-43bf-9641-d4e618b08e4f.png)

**Comment by Aadarsh805** [comment]
@Nishantjain10  Yeah that happens because of these reasons, we have listed them on footer of the webpage
![Screenshot_2022-12-20-14-15-17-252_com android chrome](https://user-images.githubusercontent.com/95094057/208623241-dad8f4a6-06be-462d-9dcd-fa371a3685d7.jpg)

**Comment by Aadarsh805** [comment]
@Nishantjain10 retweets won't count, i just saw your Twitter, saw that you haven't tweeted recently
After this username error you did tweet your GitHub wrapped, so check it it'll work now, but will generate result only on that single tweet

**Comment by Nishantjain10** [comment]
Thank you, aadarsh; I had overlooked the footer section! Also, it is now operational and generating responses from a single tweet! This project is fantastic.
