### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by Ninad-Patil** [Aadarsh805/TweetSage#83]
![Screenshot 2022-12-24 163147](https://user-images.githubusercontent.com/72431205/209432964-9a07abce-708c-483b-a49a-2dbaff3c444a.png)

I think instead of saying it like in the above screenshot we could say it like this:
 "It works by fetching the user's recent tweets from the Twitter API" 
so that it's easy to understand

**Comment by Ninad-Patil** [comment]
If approved I would love to make this change.

**Comment by Aadarsh805** [comment]
> If approved I would love to make this change.

Yes sir go ahead

**Comment by Ninad-Patil** [comment]
> > If approved I would love to make this change.
> 
> Yes sir go ahead

made a pull request
